// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_CALANDER_H
#define UI_CALANDER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Calander
extern void ui_Calander_screen_init(void);
extern void ui_Calander_screen_destroy(void);
extern lv_obj_t * ui_Calander;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

