// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_STATISTICS_H
#define UI_STATISTICS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Statistics
extern void ui_Statistics_screen_init(void);
extern void ui_Statistics_screen_destroy(void);
extern lv_obj_t * ui_Statistics;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

