// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: ebike_demo

#include "../ui.h"


// IMAGE DATA: assets/icn_ok.png
const char * ui_img_icn_ok_png = "S:assets/icn_ok.png";
