// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: ebike_demo

#include "../ui.h"


// IMAGE DATA: assets/settings_corner.png
const char * ui_img_settings_corner_png = "S:assets/settings_corner.png";
