// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Bar2 = NULL;
lv_obj_t * ui_Bar3 = NULL;
lv_obj_t * ui_Bar4 = NULL;
lv_obj_t * ui_Bar5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Chart2 = NULL;
lv_obj_t * ui_Chart2_Xaxis = NULL;
lv_obj_t * ui_Chart2_Yaxis1 = NULL;
lv_obj_t * ui_Chart2_Yaxis2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
// event funtions
void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Profiles, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Profiles_screen_init);
    }
}

void ui_event_Panel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Statistics, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Statistics_screen_init);
    }
}

void ui_event_Panel8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Main, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Main, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Main, lv_color_hex(0x00FF57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Main, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Main, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Main, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Main, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Main, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel1, 300);
    lv_obj_set_height(ui_Panel1, 40);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -190);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label1, "Profile:");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_Label2, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Label2, "Habanero");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Main);
    lv_image_set_src(ui_Image1, &ui_img_habonero_icon_scaled_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, lv_pct(-69));
    lv_obj_set_y(ui_Image1, lv_pct(12));
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Image1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image1, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel2, 300);
    lv_obj_set_height(ui_Panel2, 103);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 161);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, lv_pct(0));
    lv_obj_set_y(ui_Label3, lv_pct(-50));
    lv_obj_set_align(ui_Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label3, "Stage:");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, lv_pct(0));
    lv_obj_set_y(ui_Label7, lv_pct(-50));
    lv_obj_set_align(ui_Label7, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label7, "Ready To Harvest");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x00FF1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label4, "Time remaining:");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label8, "7 days");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, lv_pct(0));
    lv_obj_set_y(ui_Label5, lv_pct(50));
    lv_obj_set_align(ui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label5, "Time since start:");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, lv_pct(0));
    lv_obj_set_y(ui_Label9, lv_pct(50));
    lv_obj_set_align(ui_Label9, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label9, "83 days");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 451);
    lv_obj_set_height(ui_Container2, 159);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel3, lv_pct(60));
    lv_obj_set_height(ui_Panel3, lv_pct(100));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel5, lv_pct(100));
    lv_obj_set_height(ui_Panel5, lv_pct(80));
    lv_obj_set_x(ui_Panel5, lv_pct(0));
    lv_obj_set_y(ui_Panel5, lv_pct(15));
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Panel5);
    lv_bar_set_value(ui_Bar1, 40, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, lv_pct(100));
    lv_obj_set_height(ui_Bar1, lv_pct(12));
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, lv_pct(44));
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x1E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar2 = lv_bar_create(ui_Panel5);
    lv_bar_set_value(ui_Bar2, 67, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, lv_pct(100));
    lv_obj_set_height(ui_Bar2, lv_pct(12));
    lv_obj_set_x(ui_Bar2, 0);
    lv_obj_set_y(ui_Bar2, lv_pct(22));
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x360000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xF90000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar2,
                                                                                           lv_obj_get_style_pad_right(ui_Bar2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar3 = lv_bar_create(ui_Panel5);
    lv_bar_set_value(ui_Bar3, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, lv_pct(100));
    lv_obj_set_height(ui_Bar3, lv_pct(12));
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x0B0025), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x6800FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar3,
                                                                                           lv_obj_get_style_pad_right(ui_Bar3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar4 = lv_bar_create(ui_Panel5);
    lv_bar_set_value(ui_Bar4, 30, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, lv_pct(100));
    lv_obj_set_height(ui_Bar4, lv_pct(12));
    lv_obj_set_x(ui_Bar4, 0);
    lv_obj_set_y(ui_Bar4, lv_pct(-22));
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x001F06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x3CFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar4, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar4,
                                                                                           lv_obj_get_style_pad_right(ui_Bar4, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar5 = lv_bar_create(ui_Panel5);
    lv_bar_set_value(ui_Bar5, 75, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar5, lv_pct(100));
    lv_obj_set_height(ui_Bar5, lv_pct(12));
    lv_obj_set_x(ui_Bar5, 0);
    lv_obj_set_y(ui_Bar5, lv_pct(-44));
    lv_obj_set_align(ui_Bar5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar5, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar5, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar5, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar5,
                                                                                           lv_obj_get_style_pad_right(ui_Bar5, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label6 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, lv_pct(0));
    lv_obj_set_y(ui_Label6, lv_pct(-45));
    lv_obj_set_align(ui_Label6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label6, "Light Levels");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_Switch1, lv_pct(20));
    lv_obj_set_height(ui_Switch1, lv_pct(16));
    lv_obj_set_x(ui_Switch1, lv_pct(0));
    lv_obj_set_y(ui_Switch1, lv_pct(-45));
    lv_obj_set_align(ui_Switch1, LV_ALIGN_RIGHT_MID);

    ui_Panel6 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel6, lv_pct(37));
    lv_obj_set_height(ui_Panel6, lv_pct(29));
    lv_obj_set_align(ui_Panel6, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Statistics");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel7, lv_pct(37));
    lv_obj_set_height(ui_Panel7, lv_pct(29));
    lv_obj_set_align(ui_Panel7, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "8:53 PM");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel8, lv_pct(37));
    lv_obj_set_height(ui_Panel8, lv_pct(29));
    lv_obj_set_align(ui_Panel8, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Settings");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel4, 447);
    lv_obj_set_height(ui_Panel4, 257);
    lv_obj_set_x(ui_Panel4, 162);
    lv_obj_set_y(ui_Panel4, 105);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_Panel4);
    lv_obj_set_width(ui_Chart2, lv_pct(82));
    lv_obj_set_height(ui_Chart2, lv_pct(80));
    lv_obj_set_x(ui_Chart2, 0);
    lv_obj_set_y(ui_Chart2, 5);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_div_line_count(ui_Chart2, 5, 5);

    ui_Chart2_Xaxis = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart2_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart2_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart2_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart2_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart2_Xaxis, 0, 8 > 0 ? 8 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart2_Xaxis, (8 > 0 ? 8 - 1 : 0) * 4 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Xaxis, 4 >= 1 ? 4 : 1);
    ui_Chart2_Yaxis1 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart2_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart2,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart2_Yaxis2 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart2_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x0100FF),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 70, 60, 50, 60, 70, 60, 50, 60, 70, 60 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_chart_series_t * ui_Chart2_series_2 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x00C7FF),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart2_series_2_array[] = { 60, 70, 60, 50, 60, 70, 60, 50, 60, 70 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_2, ui_Chart2_series_2_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart2, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Label10 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, lv_pct(-50));
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Soil Moisture");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, lv_pct(14));
    lv_obj_set_y(ui_Label11, lv_pct(29));
    lv_obj_set_align(ui_Label11, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label11, "Setpoint");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x0002FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, lv_pct(-14));
    lv_obj_set_y(ui_Label12, lv_pct(29));
    lv_obj_set_align(ui_Label12, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label12, "Measured");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel6, ui_event_Panel6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel8, ui_event_Panel8, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_Panel1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Image1 = NULL;
    ui_Panel2 = NULL;
    ui_Label3 = NULL;
    ui_Label7 = NULL;
    ui_Label4 = NULL;
    ui_Label8 = NULL;
    ui_Label5 = NULL;
    ui_Label9 = NULL;
    ui_Container2 = NULL;
    ui_Panel3 = NULL;
    ui_Panel5 = NULL;
    ui_Bar1 = NULL;
    ui_Bar2 = NULL;
    ui_Bar3 = NULL;
    ui_Bar4 = NULL;
    ui_Bar5 = NULL;
    ui_Label6 = NULL;
    ui_Switch1 = NULL;
    ui_Panel6 = NULL;
    ui_Label13 = NULL;
    ui_Panel7 = NULL;
    ui_Label14 = NULL;
    ui_Panel8 = NULL;
    ui_Label15 = NULL;
    ui_Panel4 = NULL;
    ui_Chart2 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;

}
