// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_PROFILES_H
#define UI_PROFILES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Profiles
extern void ui_Profiles_screen_init(void);
extern void ui_Profiles_screen_destroy(void);
extern lv_obj_t * ui_Profiles;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

