// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Bar6;
extern void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container1;
extern void ui_event_Panel9(lv_event_t * e);
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image1;
extern void ui_event_Panel10(lv_event_t * e);
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Bar7;
extern void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container2;
extern void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Bar5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label13;
extern void ui_event_Panel7(lv_event_t * e);
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label14;
extern void ui_event_Panel8(lv_event_t * e);
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label15;
extern void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart2_Xaxis;
extern lv_obj_t * ui_Chart2_Yaxis1;
extern lv_obj_t * ui_Chart2_Yaxis2;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Far_Red_Light_Indicator;
extern lv_obj_t * uic_Red_Light_Indicator;
extern lv_obj_t * uic_Purple_Light_Indicator;
extern lv_obj_t * uic_Lime_Light_Indicator;
extern lv_obj_t * uic_White_Light_Indicator;
extern lv_obj_t * uic_Soil_Moisture_Chart;
extern lv_obj_t * uic_Graph_1HAgo;
extern lv_obj_t * uic_Graph_2HAgo;
extern lv_obj_t * uic_Graph_3HAgo;
extern lv_obj_t * uic_Graph_4HAgo;
extern lv_obj_t * uic_Graph_5HAgo;
extern lv_obj_t * uic_Graph_6HAgo;
extern lv_obj_t * uic_Graph_7HAgo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

