// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_STATUS_H
#define UI_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Status
extern void ui_Status_screen_init(void);
extern void ui_Status_screen_destroy(void);
extern lv_obj_t * ui_Status;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

