/*
 * Clock.h
 *
 *  Created on: Dec 22, 2025
 *      Author: jackh
 */

#ifndef INC_CLOCK_H_
#define INC_CLOCK_H_

#include "stdint.h"

#define HSE_FREQ 8000000
#define HSI_FREQ 16000000

#define PLLM				4
#define PLLN				180
#define PLLP				2
#define PLLQ				6
#define PLLR				6
#define PLLSAIN				144
#define PLLSAIP				6
#define PLLSAIQ1			2
#define PLLSAIQ2			1
#define PLLSAIR1			2
#define PLLSAIR2			4
#define PLLI2SN				192
#define PLLI2SQ1			4
#define PLLI2SQ2			1
#define PLLI2SR				2
#define PLLDSIIDF			2			// DSI VALUES ARE NOT PROGRAMMED IN CLOCK.C - THEY ARE IMPLEMENTED IN DSI_LCD.C
#define PLLDSIIDFMULTIPLIER	2
#define PLLDSINDIV			125			// /1 to /7
#define PLLDSIVCODIV		2			// x10 to x125
#define PLLDSIODF			0			// 0: /1, 1: /2, 2: /4, 3: /8
#define DSITXPRESCALER		4


#define AHBPRESCALER		1
#define APB1PRESCALER		4
#define APB1TIMERMULTIPLIER	2
#define APB2PRESCALER		2
#define APB2TIMERMULTIPLIER	2
#define CORTEXSYSTEMDIV		1

// TODO implement selectors into C file (currently not supported)

#define SAI1ASRC_SELECTOR			0 	// 0: PLLSAIQ 1: PLLI2SQ 2: I2SCKIN
#define FORTYEIGHTMHZSRC_SELECTOR	1	// 0: PLLQ 1: PLLSAIP
#define DSISRC_SELECTOR				0	// 0: DSI_PHY 1: PLLR
#define	PLLSRC_SELECTOR				1	// 0: HSI 1: HSE
#define SYSCLKSRC_SELECTOR			2   // 0: HSI 1: HSE: 2:PLL

#if PLLSAIR2 == 2
#define PLLSAIR2_CODE 0
#elif PLLSAIR2 == 4
#define PLLSAIR2_CODE 1
#elif PLLSAIR2 == 8
#define PLLSAIR2_CODE 2
#elif PLLSAIR2 == 16
#define PLLSAIR2_CODE 3
#endif

#if APB1PRESCALER == 1
#define PPRE1_CODE  0
#elif APB1PRESCALER == 2
#define PPRE1_CODE  4
#elif APB1PRESCALER == 4
#define PPRE1_CODE  5
#elif APB1PRESCALER == 8
#define PPRE1_CODE  6
#elif APB1PRESCALER == 16
#define PPRE1_CODE  7
#endif

#if APB2PRESCALER == 1
#define PPRE2_CODE  0
#elif APB2PRESCALER == 2
#define PPRE2_CODE  4
#elif APB2PRESCALER == 4
#define PPRE2_CODE  5
#elif APB2PRESCALER == 8
#define PPRE2_CODE  6
#elif APB2PRESCALER == 16
#define PPRE2_CODE  7
#endif

#if AHBPRESCALER == 1
#define HPRE_CODE  0
#elif AHBPRESCALER == 2
#define HPRE_CODE  8
#elif AHBPRESCALER == 4
#define HPRE_CODE  9
#elif AHBPRESCALER == 8
#define HPRE_CODE  10
#elif AHBPRESCALER == 16
#define HPRE_CODE  11
#elif AHBPRESCALER == 64
#define HPRE_CODE  12
#elif AHBPRESCALER == 128
#define HPRE_CODE  13
#elif AHBPRESCALER == 256
#define HPRE_CODE  14
#elif AHBPRESCALER == 512
#define HPRE_CODE  15
#endif

#if PLLSRC_SELECTOR == 0
#define PLLSRC_FREQ  HSI_FREQ
#elif PLLSRC_SELECTOR == 1
#define PLLSRC_FREQ  HSE_FREQ
#endif

#if SYSCLKSRC_SELECTOR == 0
#define SYSCLKSRC_FREQ  HSI_FREQ
#elif SYSCLKSRC_SELECTOR == 1
#define SYSCLKSRC_FREQ  HSE_FREQ
#elif SYSCLKSRC_SELECTOR == 2
#define SYSCLKSRC_FREQ  PLLSRC_FREQ / PLLM * PLLN / PLLP
#endif

#if FORTYEIGHTMHZSRC_SELECTOR == 0
#define FORTYEIGHTMHZSRC_FREQ  PLLSRC_FREQ / PLLM * PLLN / PLLQ
#elif FORTYEIGHTMHZSRC_SELECTOR == 1
#define FORTYEIGHTMHZSRC_FREQ  PLLSRC_FREQ / PLLM * PLLSAIN / PLLSAIP
#endif

#if SAI1ASRC_SELECTOR == 0
#define SAI1ASRC_FREQ  	PLLSRC_FREQ / PLLM * PLLSAIN / PLLSAIQ1 / PLLSAIQ2
#elif SAI1ASRC_SELECTOR == 1
#define SAI1ASRC_FREQ  	PLLSRC_FREQ / PLLM * PLLI2SN / PLLI2SQ1 / PLLI2SQ2
#elif SAI1ASRC_SELECTOR == 2
#define SAI1ASRC_FREQ	//todo add this value
#endif

#if DSISRC_SELECTOR == 0
#define DSISRC_FREQ HSE_FREQ/PLLDSIIDF*PLLDSIIDFMULTIPLIER*PLLDSINDIV/PLLDSIVCODIV/PLLDSIODF/8
#elif DSISRC_SELECTOR == 1
#define DSISRC_FREQ PLLSRC_FREQ / PLLM * PLLN / PLLR
#endif


#define HCLK_FREQ			SYSCLKSRC_FREQ/AHBPRESCALER
#define ETHPTPCLOCK_FREQ	HCLK_FREQ
#define CORTEXTIMER_FREQ	HCLK_FREQ/CORTEXSYSTEMDIV
#define FCLK_FREQ			HCLK_FREQ
#define APB1PERIPHERAL_FREQ	HCLK_FREQ/APB1PRESCALER
#define APB1TIMER_FREQ		HCLK_FREQ/APB1PRESCALER*APB1TIMERMULTIPLIER
#define APB2PERIPHERAL_FREQ	HCLK_FREQ/APB2PRESCALER
#define APB2TIMER_FREQ		HCLK_FREQ/APB2PRESCALER*APB2TIMERMULTIPLIER
#define SAIA_FREQ			HSE_FREQ/PLLM*PLLSAIN/PLLSAIQ1/PLLSAIQ2
#define LCDTFT_FREQ			HSE_FREQ/PLLM*PLLSAIN/PLLSAIR1/PLLSAIR2
#define DSIVCO_FREQ			HSE_FREQ/PLLDSIIDF*PLLDSIIDFMULTIPLIER*PLLDSINDIV
#define	DSILANE_FREQ		DSIVCO_FREQ/PLLDSIVCODIV/PLLDSIODF/8
#define DSITXCLK_FREQ		DSILANE_FREQ/DSITXPRESCALER
#define I2C_FREQ			APB1PERIPHERAL_FREQ


void clock_Init(void);
void millis_Init(void);
uint32_t clock___millis(void);
void clock___delay_ms(uint32_t delay);
#endif /* INC_CLOCK_H_ */
