// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Main.h"
#include "screens/ui_Settings.h"
#include "screens/ui_Statistics.h"
#include "screens/ui_Status.h"
#include "screens/ui_Calendar.h"
#include "screens/ui_Profiles.h"
#include "screens/ui_Water.h"
#include "screens/ui_Tools.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * DuckAnim_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_carolina_reaper_icon_250x250_png);    // assets/Carolina_Reaper_Icon_250x250.png
LV_IMG_DECLARE(ui_img_pause_icon_60x60_png);    // assets/Pause_Icon_60x60.png
LV_IMG_DECLARE(ui_img_play_icon_60x60_png);    // assets/Play_Icon_60x60.png
LV_IMG_DECLARE(ui_img_toolbox_icon_60x60_png);    // assets/Toolbox_Icon_60x60.png
LV_IMG_DECLARE(ui_img_statistics_icon_60x60_png);    // assets/Statistics_Icon_60x60.png
LV_IMG_DECLARE(ui_img_settings_icon_60x60_png);    // assets/Settings Icon 60x60.png
LV_IMG_DECLARE(ui_img_duck_80x80_png);    // assets/Duck_80x80.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
