// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Main_Clock;
lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_Bar6 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Bar7 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Image4 = NULL;
// event funtions
void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Profiles, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Profiles_screen_init);
    }
}

void ui_event_Panel9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Profiles, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Profiles_screen_init);
    }
}

void ui_event_Panel10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Water, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Water_screen_init);
    }
}

void ui_event_Panel5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Calendar, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Calendar_screen_init);
    }
}

void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Status, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Status_screen_init);
    }
}

void ui_event_Panel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Status, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Status_screen_init);
    }
}

void ui_event_Panel7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Status, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Status_screen_init);
    }
}

void ui_event_Panel8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Statistics, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Statistics_screen_init);
    }
}

void ui_event_Panel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Main, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x09090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Main, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Main, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Main, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Main, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Main, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar6 = lv_bar_create(ui_Main);
    lv_bar_set_value(ui_Bar6, 93, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar6, 9, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar6, 480);
    lv_obj_set_height(ui_Bar6, 10);
    lv_obj_set_y(ui_Bar6, -400);
    lv_obj_set_x(ui_Bar6, lv_pct(0));
    lv_obj_set_align(ui_Bar6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar6, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_radius(ui_Bar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0x043616), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Bar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Bar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Bar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Bar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Bar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Bar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0x07FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar6, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar6,
                                                                                           lv_obj_get_style_pad_right(ui_Bar6, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container4 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 480);
    lv_obj_set_height(ui_Container4, 790);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_Panel1, 400);
    lv_obj_set_height(ui_Panel1, 67);
    lv_obj_set_x(ui_Panel1, 98);
    lv_obj_set_y(ui_Panel1, -403);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label1, "Profile:");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_Label2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label2, "Carolina Reaper");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 400);
    lv_obj_set_height(ui_Container1, 250);
    lv_obj_set_x(ui_Container1, 4);
    lv_obj_set_y(ui_Container1, 39);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Panel9 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel9, 340);
    lv_obj_set_height(ui_Panel9, 250);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Panel9);
    lv_image_set_src(ui_Image1, &ui_img_carolina_reaper_icon_250x250_png);
    lv_obj_set_width(ui_Image1, 250);
    lv_obj_set_height(ui_Image1, 250);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Panel10 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel10, 35);
    lv_obj_set_height(ui_Panel10, 250);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar7 = lv_bar_create(ui_Panel10);
    lv_bar_set_value(ui_Bar7, 40, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar7, 15);
    lv_obj_set_height(ui_Bar7, 230);
    lv_obj_set_align(ui_Bar7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Bar7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar7, lv_color_hex(0x021941), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar7, lv_color_hex(0x0099FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar7, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar7,
                                                                                           lv_obj_get_style_pad_right(ui_Bar7, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel5 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_Panel5, 400);
    lv_obj_set_height(ui_Panel5, lv_pct(8));
    lv_obj_set_align(ui_Panel5, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x7B7B87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "TIME_ERR");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_Panel2, 400);
    lv_obj_set_height(ui_Panel2, 138);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 152);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, lv_pct(0));
    lv_obj_set_y(ui_Label3, lv_pct(-40));
    lv_obj_set_align(ui_Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label3, "Stage:");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, lv_pct(0));
    lv_obj_set_y(ui_Label7, lv_pct(-40));
    lv_obj_set_align(ui_Label7, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label7, "Ready To Harvest");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x00FF1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label4, "Time remaining:");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label8, "7 days");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, lv_pct(0));
    lv_obj_set_y(ui_Label5, lv_pct(40));
    lv_obj_set_align(ui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label5, "Time since start:");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, lv_pct(0));
    lv_obj_set_y(ui_Label9, lv_pct(40));
    lv_obj_set_align(ui_Label9, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label9, "83 days");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 400);
    lv_obj_set_height(ui_Container2, 100);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_Container2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel6, 90);
    lv_obj_set_height(ui_Panel6, 90);
    lv_obj_set_x(ui_Panel6, -155);
    lv_obj_set_y(ui_Panel6, 0);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x7B7B87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel7, 90);
    lv_obj_set_height(ui_Panel7, 90);
    lv_obj_set_x(ui_Panel7, -50);
    lv_obj_set_y(ui_Panel7, 0);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x7B7B87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel8, 90);
    lv_obj_set_height(ui_Panel8, 90);
    lv_obj_set_x(ui_Panel8, 50);
    lv_obj_set_y(ui_Panel8, 0);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x7B7B87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_Panel8);
    lv_image_set_src(ui_Image5, &ui_img_statistics_icon_60x60_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Panel3 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel3, 90);
    lv_obj_set_height(ui_Panel3, 90);
    lv_obj_set_x(ui_Panel3, 155);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x7B7B87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Panel3);
    lv_image_set_src(ui_Image4, &ui_img_settings_icon_60x60_png);
    lv_obj_set_width(ui_Image4, 60);
    lv_obj_set_height(ui_Image4, 60);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel9, ui_event_Panel9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel10, ui_event_Panel10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel5, ui_event_Panel5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel6, ui_event_Panel6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel7, ui_event_Panel7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel8, ui_event_Panel8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);
    uic_Main_Clock = ui_Label13;

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_Bar6 = NULL;
    ui_Container4 = NULL;
    ui_Panel1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Container1 = NULL;
    ui_Panel9 = NULL;
    ui_Image1 = NULL;
    ui_Panel10 = NULL;
    ui_Bar7 = NULL;
    ui_Panel5 = NULL;
    uic_Main_Clock = NULL;
    ui_Label13 = NULL;
    ui_Panel2 = NULL;
    ui_Label3 = NULL;
    ui_Label7 = NULL;
    ui_Label4 = NULL;
    ui_Label8 = NULL;
    ui_Label5 = NULL;
    ui_Label9 = NULL;
    ui_Container2 = NULL;
    ui_Panel6 = NULL;
    ui_Panel7 = NULL;
    ui_Panel8 = NULL;
    ui_Image5 = NULL;
    ui_Panel3 = NULL;
    ui_Image4 = NULL;

}
