// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Onion_Small;
lv_obj_t * uic_Pepper_Small;
lv_obj_t * ui_Profiles = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Image10 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
}

void ui_event_Panel17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
        GUI___Select_Pepper(e);
    }
}

void ui_event_Panel16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
        GUI___Select_Onion(e);
    }
}

// build funtions

void ui_Profiles_screen_init(void)
{
    ui_Profiles = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Profiles, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Profiles, lv_color_hex(0x09090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Profiles, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Profiles, lv_color_hex(0xFF8A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Profiles, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Profiles, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Profiles, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_Profiles);
    lv_obj_set_width(ui_Button3, 347);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_y(ui_Button3, 332);
    lv_obj_set_x(ui_Button3, lv_pct(0));
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Go Back");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_Profiles);
    lv_obj_set_width(ui_Panel17, 170);
    lv_obj_set_height(ui_Panel17, 170);
    lv_obj_set_x(ui_Panel17, -255);
    lv_obj_set_y(ui_Panel17, lv_pct(5));
    lv_obj_set_align(ui_Panel17, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x7B7B87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_image_create(ui_Panel17);
    lv_image_set_src(ui_Image9, &ui_img_carolina_reaper_icon_130x130_png);
    lv_obj_set_width(ui_Image9, 250);
    lv_obj_set_height(ui_Image9, 250);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Panel16 = lv_obj_create(ui_Profiles);
    lv_obj_set_width(ui_Panel16, 170);
    lv_obj_set_height(ui_Panel16, 170);
    lv_obj_set_x(ui_Panel16, -45);
    lv_obj_set_y(ui_Panel16, lv_pct(5));
    lv_obj_set_align(ui_Panel16, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x7B7B87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_image_create(ui_Panel16);
    lv_image_set_src(ui_Image10, &ui_img_onion_icon_130x130_png);
    lv_obj_set_width(ui_Image10, 250);
    lv_obj_set_height(ui_Image10, 250);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel17, ui_event_Panel17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel16, ui_event_Panel16, LV_EVENT_ALL, NULL);
    uic_Pepper_Small = ui_Image9;
    uic_Onion_Small = ui_Image10;

}

void ui_Profiles_screen_destroy(void)
{
    if(ui_Profiles) lv_obj_del(ui_Profiles);

    // NULL screen variables
    ui_Profiles = NULL;
    ui_Button3 = NULL;
    ui_Label20 = NULL;
    ui_Panel17 = NULL;
    uic_Pepper_Small = NULL;
    ui_Image9 = NULL;
    ui_Panel16 = NULL;
    uic_Onion_Small = NULL;
    ui_Image10 = NULL;

}
