// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Main_ClockSD;
lv_obj_t * uic_White_Light_Indicator;
lv_obj_t * uic_Lime_Light_Indicator;
lv_obj_t * uic_Purple_Light_Indicator;
lv_obj_t * uic_Red_Light_Indicator;
lv_obj_t * uic_Far_Red_Light_Indicator;
lv_obj_t * uic_Graph_7HAgo;
lv_obj_t * uic_Graph_6HAgo;
lv_obj_t * uic_Graph_5HAgo;
lv_obj_t * uic_Graph_4HAgo;
lv_obj_t * uic_Graph_3HAgo;
lv_obj_t * uic_Graph_2HAgo;
lv_obj_t * uic_Graph_1HAgo;
lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Chart3 = NULL;
lv_obj_t * ui_Chart3_Xaxis = NULL;
lv_obj_t * ui_Chart3_Yaxis1 = NULL;
lv_obj_t * ui_Chart3_Yaxis2 = NULL;
lv_obj_t * ui_Label55 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Label46 = NULL;
lv_obj_t * ui_Label47 = NULL;
lv_obj_t * ui_Label48 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_Label50 = NULL;
lv_obj_t * ui_Label51 = NULL;
lv_obj_t * ui_Label52 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Panel20 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Bar13 = NULL;
lv_obj_t * ui_Bar8 = NULL;
lv_obj_t * ui_Bar9 = NULL;
lv_obj_t * ui_Bar10 = NULL;
lv_obj_t * ui_WhiteLightIndicator = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_Label12 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
}

void ui_event_Panel16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Statistics, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Statistics_screen_init);
    }
}

void ui_event_Panel20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_Toggle_Bright_Mode(e);
    }
}

void ui_event_Panel17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Calendar, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Calendar_screen_init);
    }
}

void ui_event_Panel18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x09090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settings, lv_color_hex(0x5B5F65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Settings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Settings, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Settings);
    lv_obj_set_width(ui_Button2, 347);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_y(ui_Button2, 22);
    lv_obj_set_x(ui_Button2, lv_pct(0));
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Go Back");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label16, lv_pct(90));
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label16, -47);
    lv_obj_set_x(ui_Label16, lv_pct(0));
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label16, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label16, "Settings page not yet implemented");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_Panel16, 440);
    lv_obj_set_height(ui_Panel16, 253);
    lv_obj_set_x(ui_Panel16, -4);
    lv_obj_set_y(ui_Panel16, -234);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel16, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart3 = lv_chart_create(ui_Panel16);
    lv_obj_set_width(ui_Chart3, lv_pct(82));
    lv_obj_set_height(ui_Chart3, lv_pct(80));
    lv_obj_set_x(ui_Chart3, 0);
    lv_obj_set_y(ui_Chart3, 5);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart3, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);
    lv_chart_set_div_line_count(ui_Chart3, 5, 5);
    lv_obj_set_style_bg_color(ui_Chart3, lv_color_hex(0x3F3D50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart3_Xaxis = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart3_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart3_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart3_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart3_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart3_Xaxis, 0, 8 > 0 ? 8 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart3_Xaxis, (8 > 0 ? 8 - 1 : 0) * 4 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Xaxis, 4 >= 1 ? 4 : 1);
    lv_scale_set_label_show(ui_Chart3_Xaxis, false);
    ui_Chart3_Yaxis1 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart3_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart3,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart3_Yaxis2 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart3_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart3_Yaxis2, false);
    lv_chart_series_t * ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0xCDCDCD),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = { 70, 60, 50, 60, 70, 60, 50, 60, 70, 60 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);
    lv_chart_series_t * ui_Chart3_series_2 = lv_chart_add_series(ui_Chart3, lv_color_hex(0x00EEFF),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart3_series_2_array[] = { 60, 70, 60, 50, 60, 70, 60, 50, 60, 70 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_2, ui_Chart3_series_2_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart3, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart3, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Label55 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 153);
    lv_obj_set_y(ui_Label55, 107);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "Now");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, 109);
    lv_obj_set_y(ui_Label44, 108);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "ERR");

    ui_Label45 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 65);
    lv_obj_set_y(ui_Label45, 108);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "ERR");

    ui_Label46 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 22);
    lv_obj_set_y(ui_Label46, 108);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "ERR");

    ui_Label47 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, -21);
    lv_obj_set_y(ui_Label47, 108);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "ERR");

    ui_Label48 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, -66);
    lv_obj_set_y(ui_Label48, 108);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "ERR");

    ui_Label49 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -110);
    lv_obj_set_y(ui_Label49, 108);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "ERR");

    ui_Label50 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -153);
    lv_obj_set_y(ui_Label50, 108);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "ERR");

    ui_Label51 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 0);
    lv_obj_set_y(ui_Label51, lv_pct(-50));
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "Statistics: Soil Moisture");
    lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, lv_pct(14));
    lv_obj_set_y(ui_Label52, lv_pct(29));
    lv_obj_set_align(ui_Label52, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label52, "Setpoint");
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0xCDCDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label52, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, lv_pct(-14));
    lv_obj_set_y(ui_Label53, lv_pct(29));
    lv_obj_set_align(ui_Label53, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label53, "Measured");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0x00EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 440);
    lv_obj_set_height(ui_Container5, 159);
    lv_obj_set_x(ui_Container5, 3);
    lv_obj_set_y(ui_Container5, 207);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel20 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel20, lv_pct(59));
    lv_obj_set_height(ui_Panel20, lv_pct(100));
    lv_obj_set_align(ui_Panel20, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Panel20, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel20, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0xF0F67E), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Panel20, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Panel20, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel4 = lv_obj_create(ui_Panel20);
    lv_obj_set_width(ui_Panel4, lv_pct(100));
    lv_obj_set_height(ui_Panel4, lv_pct(80));
    lv_obj_set_x(ui_Panel4, lv_pct(0));
    lv_obj_set_y(ui_Panel4, lv_pct(15));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar13 = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_Bar13, 0, 255);
    lv_bar_set_value(ui_Bar13, 40, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar13, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar13, lv_pct(100));
    lv_obj_set_height(ui_Bar13, lv_pct(12));
    lv_obj_set_x(ui_Bar13, 0);
    lv_obj_set_y(ui_Bar13, lv_pct(44));
    lv_obj_set_align(ui_Bar13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Bar13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar13, lv_color_hex(0x1E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar13, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar13, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar13, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar13,
                                                                                            lv_obj_get_style_pad_right(ui_Bar13, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar8 = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_Bar8, 0, 255);
    lv_bar_set_value(ui_Bar8, 67, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar8, lv_pct(100));
    lv_obj_set_height(ui_Bar8, lv_pct(12));
    lv_obj_set_x(ui_Bar8, 0);
    lv_obj_set_y(ui_Bar8, lv_pct(22));
    lv_obj_set_align(ui_Bar8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Bar8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar8, lv_color_hex(0x360000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar8, lv_color_hex(0xF90000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar8, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar8,
                                                                                           lv_obj_get_style_pad_right(ui_Bar8, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar9 = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_Bar9, 0, 255);
    lv_bar_set_value(ui_Bar9, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar9, lv_pct(100));
    lv_obj_set_height(ui_Bar9, lv_pct(12));
    lv_obj_set_align(ui_Bar9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Bar9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar9, lv_color_hex(0x0B0025), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar9, lv_color_hex(0x6800FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar9, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar9,
                                                                                           lv_obj_get_style_pad_right(ui_Bar9, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar10 = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_Bar10, 0, 255);
    lv_bar_set_value(ui_Bar10, 30, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar10, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar10, lv_pct(100));
    lv_obj_set_height(ui_Bar10, lv_pct(12));
    lv_obj_set_x(ui_Bar10, 0);
    lv_obj_set_y(ui_Bar10, lv_pct(-22));
    lv_obj_set_align(ui_Bar10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Bar10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar10, lv_color_hex(0x001F06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar10, lv_color_hex(0x3CFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar10, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar10, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar10,
                                                                                            lv_obj_get_style_pad_right(ui_Bar10, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_WhiteLightIndicator = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_WhiteLightIndicator, 0, 255);
    lv_bar_set_value(ui_WhiteLightIndicator, 75, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_WhiteLightIndicator, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_WhiteLightIndicator, lv_pct(100));
    lv_obj_set_height(ui_WhiteLightIndicator, lv_pct(12));
    lv_obj_set_x(ui_WhiteLightIndicator, 0);
    lv_obj_set_y(ui_WhiteLightIndicator, lv_pct(-44));
    lv_obj_set_align(ui_WhiteLightIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WhiteLightIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_WhiteLightIndicator,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_WhiteLightIndicator, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhiteLightIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WhiteLightIndicator, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhiteLightIndicator, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_WhiteLightIndicator,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_WhiteLightIndicator, lv_obj_get_style_pad_right(ui_WhiteLightIndicator,
                                                                                  LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label27 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, lv_pct(0));
    lv_obj_set_y(ui_Label27, lv_pct(-47));
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Lighting");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel13, lv_pct(37));
    lv_obj_set_height(ui_Panel13, lv_pct(29));
    lv_obj_set_align(ui_Panel13, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "TBD");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel17, lv_pct(37));
    lv_obj_set_height(ui_Panel17, lv_pct(29));
    lv_obj_set_align(ui_Panel17, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x7B7B87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "TIME_ERR");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel18, lv_pct(37));
    lv_obj_set_height(ui_Panel18, lv_pct(29));
    lv_obj_set_align(ui_Panel18, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel18, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Settings");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel16, ui_event_Panel16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel20, ui_event_Panel20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel17, ui_event_Panel17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel18, ui_event_Panel18, LV_EVENT_ALL, NULL);
    uic_Graph_1HAgo = ui_Label44;
    uic_Graph_2HAgo = ui_Label45;
    uic_Graph_3HAgo = ui_Label46;
    uic_Graph_4HAgo = ui_Label47;
    uic_Graph_5HAgo = ui_Label48;
    uic_Graph_6HAgo = ui_Label49;
    uic_Graph_7HAgo = ui_Label50;
    uic_Far_Red_Light_Indicator = ui_Bar13;
    uic_Red_Light_Indicator = ui_Bar8;
    uic_Purple_Light_Indicator = ui_Bar9;
    uic_Lime_Light_Indicator = ui_Bar10;
    uic_White_Light_Indicator = ui_WhiteLightIndicator;
    uic_Main_ClockSD = ui_Label11;

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_Button2 = NULL;
    ui_Label17 = NULL;
    ui_Label16 = NULL;
    ui_Panel16 = NULL;
    ui_Chart3 = NULL;
    ui_Label55 = NULL;
    uic_Graph_1HAgo = NULL;
    ui_Label44 = NULL;
    uic_Graph_2HAgo = NULL;
    ui_Label45 = NULL;
    uic_Graph_3HAgo = NULL;
    ui_Label46 = NULL;
    uic_Graph_4HAgo = NULL;
    ui_Label47 = NULL;
    uic_Graph_5HAgo = NULL;
    ui_Label48 = NULL;
    uic_Graph_6HAgo = NULL;
    ui_Label49 = NULL;
    uic_Graph_7HAgo = NULL;
    ui_Label50 = NULL;
    ui_Label51 = NULL;
    ui_Label52 = NULL;
    ui_Label53 = NULL;
    ui_Container5 = NULL;
    ui_Panel20 = NULL;
    ui_Panel4 = NULL;
    uic_Far_Red_Light_Indicator = NULL;
    ui_Bar13 = NULL;
    uic_Red_Light_Indicator = NULL;
    ui_Bar8 = NULL;
    uic_Purple_Light_Indicator = NULL;
    ui_Bar9 = NULL;
    uic_Lime_Light_Indicator = NULL;
    ui_Bar10 = NULL;
    uic_White_Light_Indicator = NULL;
    ui_WhiteLightIndicator = NULL;
    ui_Label27 = NULL;
    ui_Panel13 = NULL;
    ui_Label10 = NULL;
    ui_Panel17 = NULL;
    uic_Main_ClockSD = NULL;
    ui_Label11 = NULL;
    ui_Panel18 = NULL;
    ui_Label12 = NULL;

}
