// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Backlight_Brightness;
lv_obj_t * uic_White_Light_Indicator;
lv_obj_t * uic_Lime_Light_Indicator;
lv_obj_t * uic_Purple_Light_Indicator;
lv_obj_t * uic_Red_Light_Indicator;
lv_obj_t * uic_Far_Red_Light_Indicator;
lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Panel20 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Bar13 = NULL;
lv_obj_t * ui_Bar8 = NULL;
lv_obj_t * ui_Bar9 = NULL;
lv_obj_t * ui_Bar10 = NULL;
lv_obj_t * ui_WhiteLightIndicator = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x09090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settings, lv_color_hex(0x5B5F65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Settings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Settings, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Settings);
    lv_obj_set_width(ui_Button2, 347);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_y(ui_Button2, 322);
    lv_obj_set_x(ui_Button2, lv_pct(0));
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Go Back");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 440);
    lv_obj_set_height(ui_Container5, 192);
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, -280);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel20 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel20, lv_pct(100));
    lv_obj_set_height(ui_Panel20, lv_pct(80));
    lv_obj_set_align(ui_Panel20, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Panel20, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x18171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0x5C5D64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel20, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0xF0F67E), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Panel20, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Panel20, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel4 = lv_obj_create(ui_Panel20);
    lv_obj_set_width(ui_Panel4, lv_pct(100));
    lv_obj_set_height(ui_Panel4, lv_pct(77));
    lv_obj_set_x(ui_Panel4, lv_pct(0));
    lv_obj_set_y(ui_Panel4, lv_pct(15));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar13 = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_Bar13, 0, 255);
    lv_bar_set_value(ui_Bar13, 40, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar13, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar13, lv_pct(100));
    lv_obj_set_height(ui_Bar13, lv_pct(12));
    lv_obj_set_x(ui_Bar13, 0);
    lv_obj_set_y(ui_Bar13, lv_pct(44));
    lv_obj_set_align(ui_Bar13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Bar13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar13, lv_color_hex(0x1E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar13, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar13, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar13, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar13,
                                                                                            lv_obj_get_style_pad_right(ui_Bar13, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar8 = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_Bar8, 0, 255);
    lv_bar_set_value(ui_Bar8, 67, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar8, lv_pct(100));
    lv_obj_set_height(ui_Bar8, lv_pct(12));
    lv_obj_set_x(ui_Bar8, 0);
    lv_obj_set_y(ui_Bar8, lv_pct(22));
    lv_obj_set_align(ui_Bar8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Bar8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar8, lv_color_hex(0x360000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar8, lv_color_hex(0xF90000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar8, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar8,
                                                                                           lv_obj_get_style_pad_right(ui_Bar8, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar9 = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_Bar9, 0, 255);
    lv_bar_set_value(ui_Bar9, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar9, lv_pct(100));
    lv_obj_set_height(ui_Bar9, lv_pct(12));
    lv_obj_set_align(ui_Bar9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Bar9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar9, lv_color_hex(0x0B0025), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar9, lv_color_hex(0x6800FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar9, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar9,
                                                                                           lv_obj_get_style_pad_right(ui_Bar9, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar10 = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_Bar10, 0, 255);
    lv_bar_set_value(ui_Bar10, 30, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar10, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar10, lv_pct(100));
    lv_obj_set_height(ui_Bar10, lv_pct(12));
    lv_obj_set_x(ui_Bar10, 0);
    lv_obj_set_y(ui_Bar10, lv_pct(-22));
    lv_obj_set_align(ui_Bar10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Bar10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar10, lv_color_hex(0x001F06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar10, lv_color_hex(0x3CFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar10, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar10, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar10,
                                                                                            lv_obj_get_style_pad_right(ui_Bar10, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_WhiteLightIndicator = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_WhiteLightIndicator, 0, 255);
    lv_bar_set_value(ui_WhiteLightIndicator, 75, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_WhiteLightIndicator, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_WhiteLightIndicator, lv_pct(100));
    lv_obj_set_height(ui_WhiteLightIndicator, lv_pct(12));
    lv_obj_set_x(ui_WhiteLightIndicator, 0);
    lv_obj_set_y(ui_WhiteLightIndicator, lv_pct(-44));
    lv_obj_set_align(ui_WhiteLightIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WhiteLightIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_WhiteLightIndicator,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_WhiteLightIndicator, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhiteLightIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WhiteLightIndicator, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhiteLightIndicator, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_WhiteLightIndicator,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_WhiteLightIndicator, lv_obj_get_style_pad_right(ui_WhiteLightIndicator,
                                                                                  LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label27 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, lv_pct(0));
    lv_obj_set_y(ui_Label27, lv_pct(-47));
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Lighting");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Settings);
    lv_slider_set_range(ui_Slider2, 50, 1000);
    lv_slider_set_value(ui_Slider2, 525, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 412);
    lv_obj_set_height(ui_Slider2, 19);
    lv_obj_set_x(ui_Slider2, 0);
    lv_obj_set_y(ui_Slider2, 147);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label6 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 88);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Backlight Brightness");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    uic_Far_Red_Light_Indicator = ui_Bar13;
    uic_Red_Light_Indicator = ui_Bar8;
    uic_Purple_Light_Indicator = ui_Bar9;
    uic_Lime_Light_Indicator = ui_Bar10;
    uic_White_Light_Indicator = ui_WhiteLightIndicator;
    uic_Backlight_Brightness = ui_Slider2;

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_Button2 = NULL;
    ui_Label17 = NULL;
    ui_Container5 = NULL;
    ui_Panel20 = NULL;
    ui_Panel4 = NULL;
    uic_Far_Red_Light_Indicator = NULL;
    ui_Bar13 = NULL;
    uic_Red_Light_Indicator = NULL;
    ui_Bar8 = NULL;
    uic_Purple_Light_Indicator = NULL;
    ui_Bar9 = NULL;
    uic_Lime_Light_Indicator = NULL;
    ui_Bar10 = NULL;
    uic_White_Light_Indicator = NULL;
    ui_WhiteLightIndicator = NULL;
    ui_Label27 = NULL;
    uic_Backlight_Brightness = NULL;
    ui_Slider2 = NULL;
    ui_Label6 = NULL;

}
