// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label16;
extern void ui_event_Panel16(lv_event_t * e);
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Chart3_Xaxis;
extern lv_obj_t * ui_Chart3_Yaxis1;
extern lv_obj_t * ui_Chart3_Yaxis2;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Bar13;
extern lv_obj_t * ui_Bar8;
extern lv_obj_t * ui_Bar9;
extern lv_obj_t * ui_Bar10;
extern lv_obj_t * ui_WhiteLightIndicator;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label10;
extern void ui_event_Panel17(lv_event_t * e);
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label11;
extern void ui_event_Panel18(lv_event_t * e);
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Slider2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Graph_1HAgo;
extern lv_obj_t * uic_Graph_2HAgo;
extern lv_obj_t * uic_Graph_3HAgo;
extern lv_obj_t * uic_Graph_4HAgo;
extern lv_obj_t * uic_Graph_5HAgo;
extern lv_obj_t * uic_Graph_6HAgo;
extern lv_obj_t * uic_Graph_7HAgo;
extern lv_obj_t * uic_Far_Red_Light_Indicator;
extern lv_obj_t * uic_Red_Light_Indicator;
extern lv_obj_t * uic_Purple_Light_Indicator;
extern lv_obj_t * uic_Lime_Light_Indicator;
extern lv_obj_t * uic_White_Light_Indicator;
extern lv_obj_t * uic_Main_ClockSD;
extern lv_obj_t * uic_Backlight_Brightness;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

