// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_TOOLS_H
#define UI_TOOLS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tools
extern void ui_Tools_screen_init(void);
extern void ui_Tools_screen_destroy(void);
extern lv_obj_t * ui_Tools;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

