// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Tools = NULL;
// event funtions

// build funtions

void ui_Tools_screen_init(void)
{
    ui_Tools = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Tools, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tools, lv_color_hex(0x09090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Tools, lv_color_hex(0x0081FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Tools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Tools, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Tools, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Tools_screen_destroy(void)
{
    if(ui_Tools) lv_obj_del(ui_Tools);

    // NULL screen variables
    ui_Tools = NULL;

}
