// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WATER_H
#define UI_WATER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Water
extern void ui_Water_screen_init(void);
extern void ui_Water_screen_destroy(void);
extern lv_obj_t * ui_Water;
extern lv_obj_t * ui_Duck;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

