/*
 * STM32H7A3_Clock_Tree.h
 *
 *  Created on: May 17, 2026
 *      Author: Jack Herron
 */

#ifndef INC_STM32H7A3_CLOCK_TREE_H_
#define INC_STM32H7A3_CLOCK_TREE_H_

/* Generated by STM32H7A3 Clock Solver. */

#define CLOCK_HSE_FREQ                          8000000UL         /* External high-speed oscillator frequency */
#define CLOCK_HSI_FREQ                          64000000UL        /* Internal high-speed oscillator frequency */
#define CLOCK_CSI_FREQ                          4000000UL         /* CSI internal oscillator frequency */
#define CLOCK_HSI48_FREQ                        48000000UL        /* Dedicated 48 MHz oscillator frequency */

#define PLL1_SOURCE                             2U                /* PLL1 clock source selection (0=HSI, CSI, HSE) */
#define PLL1_M                                  1U                /* PLL1 input divider */
#define PLL1_N                                  70U               /* PLL1 VCO multiplier */
#define PLL1_FRACN                              0U                /* PLL1 fractional divider numerator */
#define PLL1_FRACTIONAL_ENABLE                  0U                /* PLL1 fractional mode enable */
#define PLL1_P_DIV                              2U                /* PLL1 P output divider */
#define PLL1_Q_DIV                              4U                /* PLL1 Q output divider */
#define PLL1_R_DIV                              2U                /* PLL1 R output divider */

#define PLL2_SOURCE                             2U                /* PLL2 clock source selection (0=HSI, CSI, HSE) */
#define PLL2_M                                  32U               /* PLL2 input divider */
#define PLL2_N                                  129U              /* PLL2 VCO multiplier */
#define PLL2_FRACN                              0U                /* PLL2 fractional divider numerator */
#define PLL2_FRACTIONAL_ENABLE                  0U                /* PLL2 fractional mode enable */
#define PLL2_P_DIV                              2U                /* PLL2 P output divider */
#define PLL2_Q_DIV                              2U                /* PLL2 Q output divider */
#define PLL2_R_DIV                              2U                /* PLL2 R output divider */

#define PLL3_SOURCE                             2U                /* PLL3 clock source selection (0=HSI, CSI, HSE) */
#define PLL3_M                                  1U                /* PLL3 input divider */
#define PLL3_N                                  20U               /* PLL3 VCO multiplier */
#define PLL3_FRACN                              0U                /* PLL3 fractional divider numerator */
#define PLL3_FRACTIONAL_ENABLE                  0U                /* PLL3 fractional mode enable */
#define PLL3_P_DIV                              2U                /* PLL3 P output divider */
#define PLL3_Q_DIV                              2U                /* PLL3 Q output divider */
#define PLL3_R_DIV                              2U                /* PLL3 R output divider */

#define SYSCLK_SOURCE                           3U                /* System clock source selection (0=HSI, CSI, HSE, PLL1_P) */
#define CLOCK_CPU_DIV                           1U                /* CPU domain clock divider */
#define CLOCK_AHB_DIV                           1U                /* AHB bus clock divider */
#define CLOCK_APB3_DIV                          2U                /* APB3 bus clock divider */
#define CLOCK_APB1_DIV                          2U                /* APB1 bus clock divider */
#define CLOCK_APB2_DIV                          2U                /* APB2 bus clock divider */
#define CLOCK_APB4_DIV                          2U                /* APB4 bus clock divider */
#define PER_CLOCK_SOURCE                        0U                /* PER_CK clock source selection (0=HSI, CSI, HSE) */
#define CLOCK_RTC_HSE_DIV                       2U                /* RTC HSE clock divider */

#define CLOCK_SYSCLK_FREQ                       280000000UL       /* System clock frequency */
#define CLOCK_CPU_FREQ                          280000000UL       /* CPU core clock frequency */
#define CLOCK_HCLK_FREQ                         280000000UL       /* AHB bus clock frequency */
#define CLOCK_PCLK1_FREQ                        140000000UL       /* APB1 peripheral clock frequency */
#define CLOCK_PCLK2_FREQ                        140000000UL       /* APB2 peripheral clock frequency */
#define CLOCK_PCLK4_FREQ                        140000000UL       /* APB4 peripheral clock frequency */

/* Active peripheral kernel clocks. */
#define CLOCK_RTC_SOURCE                        2U                /* RTC kernel clock source selection (0=NONE, LSE, LSI, HSE_DIV) */
#define CLOCK_RTC_FREQ                          32000UL           /* RTC kernel clock frequency */

#define CLOCK_PER_CK_OUT_SOURCE                 0U                /* PER_CK source kernel clock source selection (0=HSI, CSI, HSE) */
#define CLOCK_PER_CK_OUT_FREQ                   64000000UL        /* PER_CK source kernel clock frequency */

#define CLOCK_MCO1_SOURCE                       0U                /* MCO1 kernel clock source selection (0=HSI, LSE, HSE, PLL1_Q, HSI48) */
#define CLOCK_MCO1_FREQ                         64000000UL        /* MCO1 kernel clock frequency */

#define CLOCK_FMC_SOURCE                        0U                /* FMC kernel clock source selection (0=HCLK, PLL1_Q, PLL2_R, PER_CK) */
#define CLOCK_FMC_FREQ                          280000000UL       /* FMC kernel clock frequency */

#define CLOCK_OCTOSPI_SOURCE                    0U                /* OCTOSPI1, 2 kernel clock source selection (0=HCLK, PLL1_Q, PLL2_R, PER_CK) */
#define CLOCK_OCTOSPI_FREQ                      280000000UL       /* OCTOSPI1, 2 kernel clock frequency */

#define CLOCK_SDMMC12_SOURCE                    0U                /* SDMMC1, 2 kernel clock source selection (0=PLL1_Q, PLL2_R) */
#define CLOCK_SDMMC12_FREQ                      140000000UL       /* SDMMC1, 2 kernel clock frequency */

#define CLOCK_FDCAN_SOURCE                      1U                /* FDCAN kernel clock source selection (0=HSE, PLL1_Q, PLL2_Q) */
#define CLOCK_FDCAN_FREQ                        140000000UL       /* FDCAN kernel clock frequency */

#define CLOCK_CEC_SOURCE                        1U                /* HDMI-CEC kernel clock source selection (0=LSE, LSI, CSI_DIV122) */
#define CLOCK_CEC_FREQ                          32000UL           /* HDMI-CEC kernel clock frequency */

#define CLOCK_I2C123_SOURCE                     0U                /* I2C1, 2, 3 kernel clock source selection (0=PCLK1, PLL3_R, HSI, CSI) */
#define CLOCK_I2C123_FREQ                       140000000UL       /* I2C1, 2, 3 kernel clock frequency */

#define CLOCK_I2C4_SOURCE                       0U                /* I2C4 kernel clock source selection (0=PCLK4, PLL3_R, HSI, CSI) */
#define CLOCK_I2C4_FREQ                         140000000UL       /* I2C4 kernel clock frequency */

#define CLOCK_USART16910_SOURCE                 0U                /* USART1, 6, 9, 10 kernel clock source selection (0=PCLK2, PLL2_Q, PLL3_Q, HSI, CSI, LSE) */
#define CLOCK_USART16910_FREQ                   140000000UL       /* USART1, 6, 9, 10 kernel clock frequency */

#define CLOCK_USART234578_SOURCE                0U                /* USART2, 3, 4, 5, 7, 8 kernel clock source selection (0=PCLK1, PLL2_Q, PLL3_Q, HSI, CSI, LSE) */
#define CLOCK_USART234578_FREQ                  140000000UL       /* USART2, 3, 4, 5, 7, 8 kernel clock frequency */

#define CLOCK_LPUART1_SOURCE                    0U                /* LPUART1 kernel clock source selection (0=PCLK4, PLL2_Q, PLL3_Q, HSI, CSI, LSE) */
#define CLOCK_LPUART1_FREQ                      140000000UL       /* LPUART1 kernel clock frequency */

#define CLOCK_SPI123_SOURCE                     0U                /* SPI1, 2, 3 kernel clock source selection (0=PLL1_Q, PLL2_P, PLL3_P, I2S_CKIN, PER_CK) */
#define CLOCK_SPI123_FREQ                       140000000UL       /* SPI1, 2, 3 kernel clock frequency */

#define CLOCK_SPI45_SOURCE                      0U                /* SPI4, 5 kernel clock source selection (0=PCLK2, PLL2_Q, PLL3_Q, HSI, CSI, HSE) */
#define CLOCK_SPI45_FREQ                        140000000UL       /* SPI4, 5 kernel clock frequency */

#define CLOCK_SPI6_SOURCE                       0U                /* SPI6 kernel clock source selection (0=PCLK4, PLL2_Q, PLL3_Q, HSI, CSI, HSE, I2S_CKIN) */
#define CLOCK_SPI6_FREQ                         140000000UL       /* SPI6 kernel clock frequency */

#define CLOCK_SAI1_SOURCE                       0U                /* SAI1 / DFSDM1 ACLK kernel clock source selection (0=PLL1_Q, PLL2_P, PLL3_P, I2S_CKIN, PER_CK) */
#define CLOCK_SAI1_FREQ                         140000000UL       /* SAI1 / DFSDM1 ACLK kernel clock frequency */

#define CLOCK_SAI2A_SOURCE                      0U                /* SAI2A kernel clock source selection (0=PLL1_Q, PLL2_P, PLL3_P, I2S_CKIN, PER_CK, SPDIFRX_SYMB) */
#define CLOCK_SAI2A_FREQ                        140000000UL       /* SAI2A kernel clock frequency */

#define CLOCK_SAI2B_SOURCE                      0U                /* SAI2B kernel clock source selection (0=PLL1_Q, PLL2_P, PLL3_P, I2S_CKIN, PER_CK, SPDIFRX_SYMB) */
#define CLOCK_SAI2B_FREQ                        140000000UL       /* SAI2B kernel clock frequency */

#define CLOCK_SPDIFRX_SOURCE                    0U                /* SPDIFRX kernel clock source selection (0=PLL1_Q, PLL2_R, PLL3_R, HSI) */
#define CLOCK_SPDIFRX_FREQ                      140000000UL       /* SPDIFRX kernel clock frequency */

#define CLOCK_USB_SOURCE                        2U                /* USB OTG kernel clock source selection (0=PLL1_Q, PLL3_Q, HSI48) */
#define CLOCK_USB_FREQ                          48000000UL        /* USB OTG kernel clock frequency */

#define CLOCK_RNG_SOURCE                        0U                /* RNG kernel clock source selection (0=HSI48, PLL1_Q, LSE, LSI) */
#define CLOCK_RNG_FREQ                          48000000UL        /* RNG kernel clock frequency */

#define CLOCK_ADC_SOURCE                        0U                /* ADC1, 2 kernel clock source selection (0=PLL2_P, PLL3_R, PER_CK) */
#define CLOCK_ADC_FREQ                          16125000UL        /* ADC1, 2 kernel clock frequency */

#define CLOCK_LTDC_SOURCE                       0U                /* LTDC kernel clock source selection (0=PLL3_R) */
#define CLOCK_LTDC_FREQ                         80000000UL        /* LTDC kernel clock frequency */

#define CLOCK_LPTIM1_SOURCE                     0U                /* LPTIM1 kernel clock source selection (0=PCLK1, PLL2_P, PLL3_R, LSE, LSI, PER_CK) */
#define CLOCK_LPTIM1_FREQ                       140000000UL       /* LPTIM1 kernel clock frequency */

#define CLOCK_LPTIM2_SOURCE                     0U                /* LPTIM2 kernel clock source selection (0=PCLK4, PLL2_P, PLL3_R, LSE, LSI, PER_CK) */
#define CLOCK_LPTIM2_FREQ                       140000000UL       /* LPTIM2 kernel clock frequency */

#define CLOCK_LPTIM3_SOURCE                     0U                /* LPTIM3 kernel clock source selection (0=PCLK4, PLL2_P, PLL3_R, LSE, LSI, PER_CK) */
#define CLOCK_LPTIM3_FREQ                       140000000UL       /* LPTIM3 kernel clock frequency */

#define CLOCK_SWPMI_SOURCE                      0U                /* SWPMI kernel clock source selection (0=PCLK1, HSI) */
#define CLOCK_SWPMI_FREQ                        140000000UL       /* SWPMI kernel clock frequency */

#define CLOCK_DFSDM1_SOURCE                     0U                /* DFSDM1 kernel kernel clock source selection (0=PCLK2, SYSCLK) */
#define CLOCK_DFSDM1_FREQ                       140000000UL       /* DFSDM1 kernel kernel clock frequency */

#define CLOCK_DFSDM2_SOURCE                     0U                /* DFSDM2 kernel kernel clock source selection (0=PCLK4, SYSCLK) */
#define CLOCK_DFSDM2_FREQ                       140000000UL       /* DFSDM2 kernel kernel clock frequency */

#define CLOCK_DCMI_PSSI_SOURCE                  0U                /* DCMI / PSSI kernel clock source selection (0=PCLK2, PLL2_Q, PLL3_R) */
#define CLOCK_DCMI_PSSI_FREQ                    140000000UL       /* DCMI / PSSI kernel clock frequency */

#define CLOCK_TRACE_SOURCE                      0U                /* TRACE kernel clock source selection (0=HSI, CSI, HSE, PLL1_R) */
#define CLOCK_TRACE_FREQ                        64000000UL        /* TRACE kernel clock frequency */

#endif /* INC_STM32H7A3_CLOCK_TREE_H_ */
