// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: ebike_demo

#ifndef _EBIKE_DEMO_UI_H
#define _EBIKE_DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Particle1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Particle2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Particle3_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Fash_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Wave1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Wave2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * On_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Map_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Knob_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
