// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: 3d_printer

#ifndef _3D_PRINTER_UI_H
#define _3D_PRINTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * OpaOn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * OpaOff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ScreenIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MenuIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MenuOut_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ScreenOut_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Small_Font);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
